# -*- coding: utf-8 -*-
"""LinAlg Lab 5_Arcera.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnrtdqikVvlquihday1Vf4u-SLyf7nzL

# **Arcera, Edhnaer**

# **Task 1**

Given a $\mathbb{R}=1$ vector in a 2-dimensional plane and visualize it using the cells below. In the first markdown cell below, write your vector using LaTeX. You should  represent it as a system of linear equations. In your methodology discuss the different functions that you have used, the equation of your vectors, and the flowchart for declaring and displaying your vector. Please make sure that your flowchart has only few words and not putting the entire code as it is bad practice. In your results, display and discuss the vector visualization code you made.

$$E = 4x + 8y \\ A = 9x + 3y$$

$$P = \begin{bmatrix} 4 \ 8\\9 \ 3 \\\end{bmatrix}\\ or \\
P = \left\{
    \begin{array}\\
        4x + 8y \\ 
        9x +3y
    \end{array}
\right. $$
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline


E = np.array([
              [4, 8], 
              [9, 3]
            ])

def plotgraph(l):
    plt.xlim(0, 15)
    plt.ylim(0, 15)
    plt.quiver([0, 0], [0, 0], l[:, 0], l[:, 1], 
               angles='xy', scale_units='xy', scale=1, color=['purple', 'blue'])
    plt.grid()
    plt.show()
plotgraph(E)

"""# **Task 2**

Given a $\mathbb{R}=2$ vector in a 3-dimensional plane and visualize it using the cells below. In the first markdown cell below, write your vector using LaTeX. You should  represent it as a system of linear equations. In your methodology discuss the different functions that you have used, the equation of your vectors, and the flowchart for declaring and displaying your vector. Please make sure that your flowchart has only few words and not putting the entire code as it is bad practice. In your results, display and discuss the vector visualization code you made.

$$E = 5x + 3y + 0z$$
$$A = 3x +6y + 0z$$
$$P = 0x +4y + 7z$$

$$
L = \left\{
    \begin{array}\\
        5x + 3y + 0z \\ 
        3x + 6y + 0z \\
        0x + 4y + 7z
    \end{array}
\right. $$
"""

import numpy as np
import matplotlib.pyplot as plt

L = np.array([[5, 3, 0],
              [3, 6, 0],
              [0, 4, 7]])


def plotgraph(l):
    fig = plt.figure()

    x1 = fig.gca(projection='3d')
    x1.set_xlim([0, 10])
    x1.set_ylim([0, 10])
    x1.set_zlim([0, 10])
    origin = (0, 0, 0)
    x1.quiver(origin, origin, origin,
               l[:, 0], l[:, 1], l[:, 2],
               arrow_length_ratio=0.05, colors=['purple', 'red', 'green'])
    plt.show()

plotgraph(L)